esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "key"

mqtt:
  broker: io.zat.net
  username: !secret mqtt_username
  password: !secret mqtt_password
  
ota:
  - platform: esphome
    password: "${ota_password}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xtcm"
    password: "xtcm"

captive_portal:


# Minimal example configuration with common sensors
i2c:

bme680_bsec:
  address: 0x77
  iaq_mode: static
  sample_rate: ulp
  state_save_interval: 6h
   
sensor:
  - platform: bme680_bsec
    temperature:
      name: "temp"
    pressure:
      name: "pressure"
    humidity:
      name: "humidity"
    iaq:
      name: "iaq"
      id: iaq
      on_value:
        then:
          - component.update: vcc_volt
          - delay: 15s
          - deep_sleep.enter: deep_sleep_me
    co2_equivalent:
      name: "co2_equivalent"
    breath_voc_equivalent:
      name: "breath_voc_equivalent"
    gas_resistance:
      name: "gas_resistance"

  - platform: adc
    pin: VCC
    name: "vcc_voltage"
    update_interval: never
    id: vcc_volt

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "iaq_accuracy"

  - platform: template
    name: "iaq_classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }

# Deep Sleep Configuration
deep_sleep:
  sleep_duration: 290s
  id: deep_sleep_me

status_led:
  pin: GPIO2